### ISSUE TITLE
Timeout doesn't fit into C timeval

### ISSUE THREAD

**Issue by danielpk08** [AnessZurba/zoom-batch-downloader#1]
Hey. I'm running into an issue where the downloads reach a max tries of 10 with the error message **"Download failed: timeout doesn't fit into C timeval Retrying (1/10) in 5 seconds..."** the download doesn't start as progress is at 0, although the file size is detected.

Cheers

**Comment by AnessZurba** [comment]
Please enable verbose output in your config and add the output here.

**Comment by danielpk08** [comment]
Hey. 

I have enabled verbose output. Should i just copy the output code including the errors? 

Attached is my config file for your reference.

EDIT: attached is the verbose output. I stopped the script after it ran through 15 files, all had the same results.

The only thing it managed to download was the text chat file. No M4A / MP4 was downloaded.

[verbose.txt](https://github.com/user-attachments/files/16094866/verbose.txt)
[config.txt](https://github.com/user-attachments/files/16094764/config.txt)

**Comment by AnessZurba** [comment]
You are not using the version from this repo. You are using the script from https://github.com/lanec/zoom-batch-downloader, they made changes that I'm not sure about. Please use the script from this repo and see what happens

**Comment by danielpk08** [comment]
> You are not using the version from this repo. You are using the script from https://github.com/lanec/zoom-batch-downloader, they made changes that I'm not sure about. Please use the script from this repo and see what happens

Holy crap i didn't even realize that...just tested it, and it's working :D awesome!!

What are the chances this could be loaded up online and store the files through FTP? hmmm

**Comment by AnessZurba** [comment]
I assume it could work as long as the target path is mounted correctly

**Comment by danielpk08** [comment]
Will give it a shot and report back soon! cheers

**Comment by TendSingh** [comment]
Had the same issue. Got my thing to work. As a person who barley knew what a python was I wish there was a bit more instruction on using the command prompt (i didn't even know it was called I had to ask someone). I kept having errors and finally got it to work when I learned that I had to delete the "#" to make it go lol. Just a POV from a noob.

**Comment by AnessZurba** [comment]
@TendSingh Actually I'm interested to hear more. Obviously there has to be limit on how much instruction I can add but what would you say where the big hurdles that faced you? What specific information do you wish was added to the README?

**Comment by AnessZurba** [comment]
I made some updates to the code, please let me know what do you think

**Comment by AnessZurba** [comment]
I'm closing this issue as it was resolved. You are welcome to open new issues with anything else.

**Comment by TendSingh** [comment]
> @TendSingh Actually I'm interested to hear more. Obviously there has to be limit on how much instruction I can add but what would you say where the big hurdles that faced you? What specific information do you wish was added to the README?

Just the "#" mainly and how to paste in the code in the command prompt (Making sure it's pulling from the correct "requirements.txt" by clarifying to open the command prompt directly from that folder - not sure if I'm saying right but that's how I understand it) 

I think the additional updates are helpful! Thanks for building this

**Comment by AnessZurba** [comment]
@TendSingh Note that now there is a beginner's helper script, where you don't need to open the terminal at all
I also added a note about `#` in the config template file.
